version: "3.7"
services:

 

  ##############
  ## Services ##
  ##############

  kv:
    image: dgoldstein1/twowaykv:0.2.2
    ports:
      - 5001:5001
    depends_on:
      - prom
    environment:
      - GRAPH_DB_STORE_DIR=/tmp/twowaykv
    volumes:
      - ./out/twowaykv:/tmp/twowaykv

  graph:
    image: dgoldstein1/biggraph:0.1.4
    ports:
      - 5000:5000
      - 8001:8001
    depends_on:
      - prom
    environment:
      - GRAPH_SAVE_PATH=/data/wikipedia_graph.graph
      - GRAPH_SAVE_INTERVAL=60
    volumes:
      - ./out/biggraph/:/data/

  ################
  ## Monitoring ##
  ################

  prom:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    entrypoint: "/bin/prometheus --log.level=debug --config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.2.4
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prom
    ports:
    - "3000:3000"
