version: "3.7"
services:

  ##############
  ## Crawlers ##
  ##############

  crawler:
    image: dgoldstein1/crawler:latest
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - MAX_APPROX_NODES=10
      - COMMAND=wikipedia
      - METRICS_PORT=8001
      - PARALLELISM=16
      - MS_DELAY=5


  ##############
  ## Services ##
  ##############

  kv:
    image: dgoldstein1/twowaykv:latest
    ports:
      - 5001:5001

  graph:
    image: dgoldstein1/biggraph:latest
    ports:
      - 5000:5000
      - 8001:8001