{
 "title": "Crawler Backend Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Big Graph Request Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (http_status) (flask_request_count_total{http_status=~\"2..\"}) / sum by (http_status) (flask_request_count_total)) * 100"
    }
   ]
  },
  {
   "title": "Nodes Added",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "number_of_nodes" },
    {}
   ]
  },
  {
   "title": "KV Request Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (http_status) (gin_requests_total{code=~\"2..\"}) / sum by (http_status) (gin_requests_total)) * 100"
    }
   ]
  },
  {
   "title": "Max Tree Depth",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max_over_time(golang_max_depth[52w])"
    }
   ]
  },
  {
   "title": "Number of Edges",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "number_of_edges" }
   ]
  },
  {
   "title": "Nodes Added  / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(number_of_nodes[1m])" },
    { "expr": "rate(golang_nodes_added[1m])" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_request_latency_seconds_sum[1m])",
     "legendFormat": "Big Graph"
    },
    {
     "expr": "rate(gin_request_duration_seconds_sum[1m])",
     "legendFormat": "KV"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_request_count_total[1m])"
    },
    { "expr": "rate(gin_requests_total[1m])" }
   ]
  }
 ]
}