global:
  scrape_interval: 2s

scrape_configs:

  - job_name: kv
    static_configs:
      - targets:
          - kv:5001

  - job_name: biggraph
    static_configs:
      - targets:
          - graph:5000
